{
 "title": "Mission Control",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - avg by (instance) (\r\n  rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\r\n) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes\r\n- node_memory_MemAvailable_bytes) / 1024^2",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{}[5m])",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Dropped packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_transmit_drop_total[5m]))",
     "legendFormat": "Tx dropped"
    },
    {
     "expr": "sum by (instance) (rate(node_network_receive_drop_total[5m]))",
     "legendFormat": "Rx dropped"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available\r\n/\r\nkube_deployment_spec_replicas",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Pod RAM",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\r\n  container_memory_working_set_bytes{container!=\"\"}\r\n) / 1024^2",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\"}\r\n - node_filesystem_free_bytes{mountpoint=\"/\"}) / 1024^3",
     "legendFormat": "Disk usage"
    }
   ]
  },
  {
   "title": "Tx/Rx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_transmit_bytes_total{device!~\"lo\"}[5m])) / 1024^2",
     "legendFormat": "Tx"
    },
    {
     "expr": "sum by (instance) (rate(node_network_receive_bytes_total{device!~\"lo\"}[5m])) / 1024^2",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Pod RAM graph",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "topk(10, sum by (namespace, pod) (\r\n  container_memory_working_set_bytes{container!=\"\"}\r\n) / 1024^2)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU usage graph",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "targets": [
    {
     "expr": "topk(10,\r\n  sum by (namespace, pod) (\r\n    rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])\r\n  )\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "topk(5, sum by (namespace, pod) (\r\n  increase(kube_pod_container_status_restarts_total[5m])\r\n))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}