apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: ehpc@ehpc.io
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          webhook:
            groupName: acme.bwolf.me
            solverName: gandi
            config:
              patSecretRef:
                name: gandi-credentials
                key: pat
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - kind: Gateway
                name: main-gateway
                namespace: default
