apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ehpc-io-hpa
  namespace: ehpc-io
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ehpc-io-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
