apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ehpc-io
  namespace: ehpc-io
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ehpc.io`)
      kind: Rule
      services:
        - name: ehpc-io
          port: 80
      middlewares:
        - name: middleware
  tls:
    certResolver: letsencrypt-prod
