apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ehpc-io-pod
  name: ehpc-io-pod
  annotations:
    io.containers.autoupdate: "registry"
spec:
  containers:
    - image: ghcr.io/ehpc/ehpc.io:prod
      name: main-site
      ports:
        - containerPort: 80
          hostPort: 8080
      livenessProbe:
        httpGet: { path: "/main-health", port: 80 }
        initialDelaySeconds: 5
        periodSeconds: 30
        timeoutSeconds: 3
        failureThreshold: 3
